Association Rules

Let's say you are a machine learning engineer working for a clothing company and you want to adopt new strategies to improve the company's profit.

Use this dataset and the association rules mining to find new marketing plans. 

Note that one of the strategies can be based on which items should be put together

dataset = [['Skirt', 'Sneakers', 'Scarf', 'Pants', 'Hat'],

    ['Sunglasses', 'Skirt', 'Sneakers', 'Pants', 'Hat'],

    ['Dress', 'Sandals', 'Scarf', 'Pants', 'Heels'],

    ['Dress', 'Necklace', 'Earrings', 'Scarf', 'Hat', 'Heels', 'Hat'],

   ['Earrings', 'Skirt', 'Skirt', 'Scarf', 'Shirt', 'Pants']]

In [153]:
dataset = [['Skirt', 'Sneakers', 'Scarf', 'Pants', 'Hat'],
['Sunglasses', 'Skirt', 'Sneakers', 'Pants', 'Hat'],
['Dress', 'Sandals', 'Scarf', 'Pants', 'Heels'],
['Dress', 'Necklace', 'Earrings', 'Scarf', 'Hat', 'Heels', 'Hat'],
['Earrings', 'Skirt', 'Skirt', 'Scarf', 'Shirt', 'Pants']]

On va compter le nombre d'occurences par nom qui revient dans ma datalist

In [157]:
dataframe = pd.DataFrame(dataset, columns  = None)

In [160]:
dataset.category.value_counts()

AttributeError: 'list' object has no attribute 'category'

In [152]:
x[3]

IndexError: index 3 is out of bounds for axis 0 with size 1

In [148]:
a = x.to_list()

In [149]:
a

[1]

In [7]:
#Apriori preparation
import mlxtend
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
te=TransactionEncoder()
te_ary=te.fit(dataset).transform(dataset)    #Apply one-hot-encoding on our dataset
df=pd.DataFrame(te_ary, columns=te.columns_)  #Creating a new DataFrame from our Numpy array
df

,Dress,Earrings,Hat,Heels,Necklace,Pants,Sandals,Scarf,Shirt,Skirt,Sneakers,Sunglasses
0,False,False,True,False,False,True,False,True,False,True,True,False
1,False,False,True,False,False,True,False,False,False,True,True,True
2,True,False,False,True,False,True,True,True,False,False,False,False
3,True,True,True,True,True,False,False,True,False,False,False,False
4,False,True,False,False,False,True,False,True,True,True,False,False

In [8]:
#Support code
from mlxtend.frequent_patterns import apriori
apriori(df, min_support=0.6)

   support itemsets
0      0.6      (2)
1      0.8      (5)
2      0.8      (7)
3      0.6      (9)
4      0.6   (5, 7)
5      0.6   (9, 5)

In [9]:
#Support with column names
frequent_itemsets=apriori(df, min_support=0.6, use_colnames=True) #Instead of column indices we can use column names.
frequent_itemsets

   support        itemsets
0      0.6           (Hat)
1      0.8         (Pants)
2      0.8         (Scarf)
3      0.6         (Skirt)
4      0.6  (Scarf, Pants)
5      0.6  (Skirt, Pants)

Conclusion: 
80% des clients ont acheté un pantalon.
80% des clients ont acheté une écharpe

In [10]:
#Confidence code:
from mlxtend.frequent_patterns import association_rules 
association_rules(frequent_itemsets,metric="confidence",min_threshold=0.7) # associate itemsets with confidence over 70%.

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(Scarf),(Pants),0.8,0.8,0.6,0.75,0.9375,-0.04,0.8,-0.25
1,(Pants),(Scarf),0.8,0.8,0.6,0.75,0.9375,-0.04,0.8,-0.25
2,(Skirt),(Pants),0.6,0.8,0.6,1.00,1.2500,0.12,inf,0.50
3,(Pants),(Skirt),0.8,0.6,0.6,0.75,1.2500,0.12,1.6,1.00

Interpretation:
Ligne 2 : 100% dans paniers qui contiennent une jupe contiennent un pantalon.
A l'inverse, 75% des paniers qui contiennent un pantalon contiennent  une jupe

Interprétation antecedent support: 80% des paniers contiennent des écharpes, pantalons, et 60% contiennent des jupes
Interprétation consequent support: même interprétation que pour la colonne précedente : 80% des paniers contiennent pantalons et écharpes, 60% contiennent jupe.

Support : c'est la combinaison des deux : 
60% des paniers contiennent à la fois écharpe et pantalon
60% des paniers contiennent à la fois jupe et pantalon

Confidence: 
ligne 2 : 100%  des  client qui ont acheté une  jupe  ont un pantalon
75% des clients qui ont acheté un pantalon ont acheté une jupe.

Lift : il y a plus de chance que les clients achètent des pantalons et  jupes ensemble  plutôt que séparemment.
En revanche,  il y a plus de chance que les clients achètent un pantalon et écharpe séparemment plutot que ensemble.

###  2eme exercice

In [20]:
import pandas as pd

In [21]:
new_df = pd.read_csv(r'/Users/guillaume/Desktop/GoMycode/Intelligence Artificielle/FichiersCsv/APRIORI_Algo_Market_Basket_Optimisation.csv', header = None)

In [22]:
new_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,butter,light mayo,fresh bread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7497,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7500,eggs,frozen smoothie,yogurt cake,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
new_df.fillna(value = '', inplace=True)

In [24]:
new_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,,,,,,,,,,,,,,,,,
2,chutney,,,,,,,,,,,,,,,,,,,
3,turkey,avocado,,,,,,,,,,,,,,,,,,
4,mineral water,milk,energy bar,whole wheat rice,green tea,,,,,,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,butter,light mayo,fresh bread,,,,,,,,,,,,,,,,,
7497,burgers,frozen vegetables,eggs,french fries,magazines,green tea,,,,,,,,,,,,,,
7498,chicken,,,,,,,,,,,,,,,,,,,
7499,escalope,green tea,,,,,,,,,,,,,,,,,,
7500,eggs,frozen smoothie,yogurt cake,low fat yogurt,,,,,,,,,,,,,,,,

In [25]:
test  = pd.DataFrame.to_numpy(new_df)

In [26]:
test

array([['shrimp', 'almonds', 'avocado', ..., 'frozen smoothie',
        'spinach', 'olive oil'],
       ['burgers', 'meatballs', 'eggs', ..., '', '', ''],
       ['chutney', '', '', ..., '', '', ''],
       ...,
       ['chicken', '', '', ..., '', '', ''],
       ['escalope', 'green tea', '', ..., '', '', ''],
       ['eggs', 'frozen smoothie', 'yogurt cake', ..., '', '', '']],
      dtype=object)

In [27]:
#Apriori preparation
import mlxtend
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
te=TransactionEncoder()
te_ary=te.fit(test).transform(test)    #Apply one-hot-encoding on our dataset
df=pd.DataFrame(te_ary, columns=te.columns_)  #Creating a new DataFrame from our Numpy array
df

,,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,False,True,True,False,True,False,False,False,False,...,False,True,False,False,True,False,False,True,False,False
1,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,True,False,False,False,False,True,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
4,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7497,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7498,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7499,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7500,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [28]:
df = df.drop('', axis=1)

In [29]:
df

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,True,True,False,True,False,False,False,False,False,...,False,True,False,False,True,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7497,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7498,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7499,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7500,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

Calcul des supports sur l'ensemble des courses de mes clients.

In [31]:
from mlxtend.frequent_patterns import apriori
apriori(df, min_support=0.03)

     support   itemsets
0   0.033329        (4)
1   0.033729       (12)
2   0.087188       (15)
3   0.030129       (16)
4   0.081056       (17)
5   0.046794       (22)
6   0.059992       (23)
7   0.163845       (25)
8   0.080389       (30)
9   0.051060       (31)
10  0.031862       (33)
11  0.179709       (37)
12  0.079323       (40)
13  0.170911       (43)
14  0.043061       (45)
15  0.063325       (48)
16  0.095321       (49)
17  0.052393       (51)
18  0.132116       (54)
19  0.098254       (55)
20  0.049460       (59)
21  0.047460       (60)
22  0.032396       (61)
23  0.076523       (65)
24  0.129583       (71)
25  0.238368       (72)
26  0.065858       (81)
27  0.095054       (82)
28  0.042528       (92)
29  0.071457       (97)
30  0.050527       (99)
31  0.174110      (100)
32  0.030396      (106)
33  0.068391      (108)
34  0.062525      (110)
35  0.058526      (116)
36  0.033196   (25, 37)
37  0.034395   (25, 43)
38  0.032129   (25, 71)
39  0.052660   (72, 25)
40  0.039195  (25, 100)
41  0.036395   (43, 37)
42  0.030796   (37, 71)
43  0.050927   (72, 37)
44  0.036528  (100, 37)
45  0.033729   (72, 43)
46  0.035729   (72, 49)
47  0.031063   (72, 54)
48  0.040928   (72, 55)
49  0.039195  (100, 55)
50  0.047994   (72, 71)
51  0.035462  (100, 71)
52  0.033729   (72, 82)
53  0.059725  (72, 100)

Calcul des supports avec les noms des produits

In [32]:
listesupport = apriori(df, min_support=0.03, use_colnames=True)

In [33]:
listesupport

     support                            itemsets
0   0.033329                           (avocado)
1   0.033729                          (brownies)
2   0.087188                           (burgers)
3   0.030129                            (butter)
4   0.081056                              (cake)
5   0.046794                         (champagne)
6   0.059992                           (chicken)
7   0.163845                         (chocolate)
8   0.080389                           (cookies)
9   0.051060                       (cooking oil)
10  0.031862                    (cottage cheese)
11  0.179709                              (eggs)
12  0.079323                          (escalope)
13  0.170911                      (french fries)
14  0.043061                       (fresh bread)
15  0.063325                   (frozen smoothie)
16  0.095321                 (frozen vegetables)
17  0.052393                     (grated cheese)
18  0.132116                         (green tea)
19  0.098254                       (ground beef)
20  0.049460                     (herb & pepper)
21  0.047460                             (honey)
22  0.032396                          (hot dogs)
23  0.076523                    (low fat yogurt)
24  0.129583                              (milk)
25  0.238368                     (mineral water)
26  0.065858                         (olive oil)
27  0.095054                          (pancakes)
28  0.042528                            (salmon)
29  0.071457                            (shrimp)
30  0.050527                              (soup)
31  0.174110                         (spaghetti)
32  0.030396                      (tomato juice)
33  0.068391                          (tomatoes)
34  0.062525                            (turkey)
35  0.058526                  (whole wheat rice)
36  0.033196                   (chocolate, eggs)
37  0.034395           (chocolate, french fries)
38  0.032129                   (chocolate, milk)
39  0.052660          (chocolate, mineral water)
40  0.039195              (spaghetti, chocolate)
41  0.036395                (french fries, eggs)
42  0.030796                        (eggs, milk)
43  0.050927               (mineral water, eggs)
44  0.036528                   (spaghetti, eggs)
45  0.033729       (mineral water, french fries)
46  0.035729  (frozen vegetables, mineral water)
47  0.031063          (green tea, mineral water)
48  0.040928        (ground beef, mineral water)
49  0.039195            (ground beef, spaghetti)
50  0.047994               (mineral water, milk)
51  0.035462                   (spaghetti, milk)
52  0.033729           (mineral water, pancakes)
53  0.059725          (spaghetti, mineral water)

In [105]:
#Confidence code:
from mlxtend.frequent_patterns import association_rules 
dfconfidence =  association_rules(listesupport,metric="confidence",min_threshold=0.01)

In [111]:
dfconfidence.sort_values(by = 'confidence', ascending = False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
24,(ground beef),(mineral water),0.098254,0.238368,0.040928,0.416554,1.747522,0.017507,1.305401,0.474369
26,(ground beef),(spaghetti),0.098254,0.174110,0.039195,0.398915,2.291162,0.022088,1.373997,0.624943
21,(frozen vegetables),(mineral water),0.095321,0.238368,0.035729,0.374825,1.572463,0.013007,1.218270,0.402413
29,(milk),(mineral water),0.129583,0.238368,0.047994,0.370370,1.553774,0.017105,1.209650,0.409465
33,(pancakes),(mineral water),0.095054,0.238368,0.033729,0.354839,1.488616,0.011071,1.180529,0.362712
35,(spaghetti),(mineral water),0.174110,0.238368,0.059725,0.343032,1.439085,0.018223,1.159314,0.369437
7,(chocolate),(mineral water),0.163845,0.238368,0.052660,0.321400,1.348332,0.013604,1.122357,0.308965
14,(eggs),(mineral water),0.179709,0.238368,0.050927,0.283383,1.188845,0.008090,1.062815,0.193648
30,(milk),(spaghetti),0.129583,0.174110,0.035462,0.273663,1.571779,0.012900,1.137061,0.417935
34,(mineral water),(spaghetti),0.238368,0.174110,0.059725,0.250559,1.439085,0.018223,1.102008,0.400606
4,(milk),(chocolate),0.129583,0.163845,0.032129,0.247942,1.513276,0.010898,1.111823,0.389677
8,(chocolate),(spaghetti),0.163845,0.174110,0.039195,0.239219,1.373952,0.010668,1.085581,0.325505
13,(milk),(eggs),0.129583,0.179709,0.030796,0.237654,1.322437,0.007509,1.076009,0.280119
23,(green tea),(mineral water),0.132116,0.238368,0.031063,0.235116,0.986357,-0.000430,0.995748,-0.015688
27,(spaghetti),(ground beef),0.174110,0.098254,0.039195,0.225115,2.291162,0.022088,1.163716,0.682343
9,(spaghetti),(chocolate),0.174110,0.163845,0.039195,0.225115,1.373952,0.010668,1.079070,0.329550
6,(mineral water),(chocolate),0.238368,0.163845,0.052660,0.220917,1.348332,0.013604,1.073256,0.339197
15,(mineral water),(eggs),0.238368,0.179709,0.050927,0.213647,1.188845,0.008090,1.043158,0.208562
11,(french fries),(eggs),0.170911,0.179709,0.036395,0.212949,1.184961,0.005681,1.042232,0.188267
3,(chocolate),(french fries),0.163845,0.170911,0.034395,0.209927,1.228284,0.006393,1.049383,0.222275
17,(spaghetti),(eggs),0.174110,0.179709,0.036528,0.209801,1.167446,0.005239,1.038081,0.173666
31,(spaghetti),(milk),0.174110,0.129583,0.035462,0.203675,1.571779,0.012900,1.093043,0.440468
16,(eggs),(spaghetti),0.179709,0.174110,0.036528,0.203264,1.167446,0.005239,1.036592,0.174852
1,(chocolate),(eggs),0.163845,0.179709,0.033196,0.202604,1.127397,0.003751,1.028711,0.135143
10,(eggs),(french fries),0.179709,0.170911,0.036395,0.202522,1.184961,0.005681,1.039640,0.190286
28,(mineral water),(milk),0.238368,0.129583,0.047994,0.201342,1.553774,0.017105,1.089850,0.467950
2,(french fries),(chocolate),0.170911,0.163845,0.034395,0.201248,1.228284,0.006393,1.046827,0.224169
19,(french fries),(mineral water),0.170911,0.238368,0.033729,0.197348,0.827912,-0.007011,0.948894,-0.200452
5,(chocolate),(milk),0.163845,0.129583,0.032129,0.196094,1.513276,0.010898,1.082736,0.405645
0,(eggs),(chocolate),0.179709,0.163845,0.033196,0.184718,1.127397,0.003751,1.025603,0.137757
25,(mineral water),(ground beef),0.238368,0.098254,0.040928,0.171700,1.747522,0.017507,1.088672,0.561638
12,(eggs),(milk),0.179709,0.129583,0.030796,0.171365,1.322437,0.007509,1.050423,0.297236
20,(mineral water),(frozen vegetables),0.238368,0.095321,0.035729,0.149888,1.572463,0.013007,1.064189,0.477993
32,(mineral water),(pancakes),0.238368,0.095054,0.033729,0.141499,1.488616,0.011071,1.054100,0.430963
18,(mineral water),(french fries),0.238368,0.170911,0.033729,0.141499,0.827912,-0.007011,0.965741,-0.214399
22,(mineral water),(green tea),0.238368,0.132116,0.031063,0.130313,0.986357,-0.000430,0.997927,-0.017837

In [112]:
dfconfidence.sort_values(by = 'lift', ascending = False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
27,(spaghetti),(ground beef),0.174110,0.098254,0.039195,0.225115,2.291162,0.022088,1.163716,0.682343
26,(ground beef),(spaghetti),0.098254,0.174110,0.039195,0.398915,2.291162,0.022088,1.373997,0.624943
25,(mineral water),(ground beef),0.238368,0.098254,0.040928,0.171700,1.747522,0.017507,1.088672,0.561638
24,(ground beef),(mineral water),0.098254,0.238368,0.040928,0.416554,1.747522,0.017507,1.305401,0.474369
21,(frozen vegetables),(mineral water),0.095321,0.238368,0.035729,0.374825,1.572463,0.013007,1.218270,0.402413
20,(mineral water),(frozen vegetables),0.238368,0.095321,0.035729,0.149888,1.572463,0.013007,1.064189,0.477993
31,(spaghetti),(milk),0.174110,0.129583,0.035462,0.203675,1.571779,0.012900,1.093043,0.440468
30,(milk),(spaghetti),0.129583,0.174110,0.035462,0.273663,1.571779,0.012900,1.137061,0.417935
29,(milk),(mineral water),0.129583,0.238368,0.047994,0.370370,1.553774,0.017105,1.209650,0.409465
28,(mineral water),(milk),0.238368,0.129583,0.047994,0.201342,1.553774,0.017105,1.089850,0.467950
4,(milk),(chocolate),0.129583,0.163845,0.032129,0.247942,1.513276,0.010898,1.111823,0.389677
5,(chocolate),(milk),0.163845,0.129583,0.032129,0.196094,1.513276,0.010898,1.082736,0.405645
32,(mineral water),(pancakes),0.238368,0.095054,0.033729,0.141499,1.488616,0.011071,1.054100,0.430963
33,(pancakes),(mineral water),0.095054,0.238368,0.033729,0.354839,1.488616,0.011071,1.180529,0.362712
34,(mineral water),(spaghetti),0.238368,0.174110,0.059725,0.250559,1.439085,0.018223,1.102008,0.400606
35,(spaghetti),(mineral water),0.174110,0.238368,0.059725,0.343032,1.439085,0.018223,1.159314,0.369437
9,(spaghetti),(chocolate),0.174110,0.163845,0.039195,0.225115,1.373952,0.010668,1.079070,0.329550
8,(chocolate),(spaghetti),0.163845,0.174110,0.039195,0.239219,1.373952,0.010668,1.085581,0.325505
7,(chocolate),(mineral water),0.163845,0.238368,0.052660,0.321400,1.348332,0.013604,1.122357,0.308965
6,(mineral water),(chocolate),0.238368,0.163845,0.052660,0.220917,1.348332,0.013604,1.073256,0.339197
13,(milk),(eggs),0.129583,0.179709,0.030796,0.237654,1.322437,0.007509,1.076009,0.280119
12,(eggs),(milk),0.179709,0.129583,0.030796,0.171365,1.322437,0.007509,1.050423,0.297236
3,(chocolate),(french fries),0.163845,0.170911,0.034395,0.209927,1.228284,0.006393,1.049383,0.222275
2,(french fries),(chocolate),0.170911,0.163845,0.034395,0.201248,1.228284,0.006393,1.046827,0.224169
14,(eggs),(mineral water),0.179709,0.238368,0.050927,0.283383,1.188845,0.008090,1.062815,0.193648
15,(mineral water),(eggs),0.238368,0.179709,0.050927,0.213647,1.188845,0.008090,1.043158,0.208562
11,(french fries),(eggs),0.170911,0.179709,0.036395,0.212949,1.184961,0.005681,1.042232,0.188267
10,(eggs),(french fries),0.179709,0.170911,0.036395,0.202522,1.184961,0.005681,1.039640,0.190286
16,(eggs),(spaghetti),0.179709,0.174110,0.036528,0.203264,1.167446,0.005239,1.036592,0.174852
17,(spaghetti),(eggs),0.174110,0.179709,0.036528,0.209801,1.167446,0.005239,1.038081,0.173666
0,(eggs),(chocolate),0.179709,0.163845,0.033196,0.184718,1.127397,0.003751,1.025603,0.137757
1,(chocolate),(eggs),0.163845,0.179709,0.033196,0.202604,1.127397,0.003751,1.028711,0.135143
23,(green tea),(mineral water),0.132116,0.238368,0.031063,0.235116,0.986357,-0.000430,0.995748,-0.015688
22,(mineral water),(green tea),0.238368,0.132116,0.031063,0.130313,0.986357,-0.000430,0.997927,-0.017837
19,(french fries),(mineral water),0.170911,0.238368,0.033729,0.197348,0.827912,-0.007011,0.948894,-0.200452
18,(mineral water),(french fries),0.238368,0.170911,0.033729,0.141499,0.827912,-0.007011,0.965741,-0.214399

On va refaire l'exercice mais sans l'eau minérale qui "pollue" l'analyse de nos résultats.

In [115]:
df2 = df.drop('mineral water', axis = 1)

In [117]:
listesupport =  apriori(df2, min_support=0.01, use_colnames=True)
listesupport

      support                       itemsets
0    0.020397                      (almonds)
1    0.033329                      (avocado)
2    0.010799               (barbecue sauce)
3    0.014265                    (black tea)
4    0.011465                   (body spray)
..        ...                            ...
206  0.020931          (spaghetti, tomatoes)
207  0.016531            (turkey, spaghetti)
208  0.014131  (spaghetti, whole wheat rice)
209  0.010532   (eggs, chocolate, spaghetti)
210  0.010932   (milk, chocolate, spaghetti)

[211 rows x 2 columns]

In [126]:
df2confidence2 =  association_rules(listesupport,metric="confidence",min_threshold=0.30)

In [127]:
df2confidence2.sort_values(by = 'confidence', ascending = False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
5,(ground beef),(spaghetti),0.098254,0.174110,0.039195,0.398915,2.291162,0.022088,1.373997,0.624943
9,(red wine),(spaghetti),0.028130,0.174110,0.010265,0.364929,2.095966,0.005368,1.300468,0.538028
8,(olive oil),(spaghetti),0.065858,0.174110,0.022930,0.348178,1.999758,0.011464,1.267048,0.535186
13,"(chocolate, milk)",(spaghetti),0.032129,0.174110,0.010932,0.340249,1.954217,0.005338,1.251821,0.504495
0,(burgers),(eggs),0.087188,0.179709,0.028796,0.330275,1.837830,0.013128,1.224818,0.499424
6,(herb & pepper),(spaghetti),0.049460,0.174110,0.016264,0.328841,1.888695,0.007653,1.230543,0.495018
4,(herb & pepper),(ground beef),0.049460,0.098254,0.015998,0.323450,3.291994,0.011138,1.332860,0.732460
12,"(eggs, chocolate)",(spaghetti),0.033196,0.174110,0.010532,0.317269,1.822232,0.004752,1.209686,0.466715
10,(salmon),(spaghetti),0.042528,0.174110,0.013465,0.316614,1.818472,0.006060,1.208527,0.470079
3,(grated cheese),(spaghetti),0.052393,0.174110,0.016531,0.315522,1.812196,0.007409,1.206597,0.472963
2,(turkey),(eggs),0.062525,0.179709,0.019464,0.311301,1.732245,0.008228,1.191072,0.450907
1,(cooking oil),(spaghetti),0.051060,0.174110,0.015865,0.310705,1.784531,0.006975,1.198166,0.463284
14,"(milk, spaghetti)",(chocolate),0.035462,0.163845,0.010932,0.308271,1.881480,0.005122,1.208790,0.485728
11,(tomatoes),(spaghetti),0.068391,0.174110,0.020931,0.306043,1.757755,0.009023,1.190117,0.462740
7,(soup),(milk),0.050527,0.129583,0.015198,0.300792,2.321232,0.008651,1.244861,0.599484